### PR TITLE
Adding History keeping and better Background support

### PR DESCRIPTION
**Pull request by Slidee**
Hello,

First of all thanks for your work on this plugin which really helps me.
I've, for my needs added some interesting functionalities : 
 - I now keep the step counter history on "SherdPreferences" keeping steps and offset for each day
 - I enhanced the background task to relaunch automatically and also to automatically launch on startup so the steps are always counted.

I let you put an eye on it then choose if you wish to merge or not.
I did not change the package name, so it's still your's.

Thanks, bye

### CODE REVIEW

**Comment by Slidee** [comment]
by the way, if you want to merge the pul request, you may change the repo url in the Readme.md to be your's

**Comment by texh** [comment]
Looks good :) Thanks for merging back your changes.

Any reason you didn't use SQLite for storing of data? That way you could implement something like getStepcountForDate/DateRange, though I guess it's possible the way it is.

If I find the time I may reimplement the former functionality of returning number of steps since the service was started, but as a more general use plugin the work you've done is great.

Best
Jarrod

**Comment by Slidee** [comment]
The only reason why i didn't use SQLite for storing is time, it was easier
and quicker for me to store data that way.

It could be a great update to store using SQLite (maybe when i'll have a
little bit more of time i'll do it).

To get the number of steps since the phone's start / the service starts (if
no phone's shutdown) you may use offset+steps (which is what you used to
return). But of course it could be good to get the number of steps from app
install (a SQLite SUM(steps) would do the trick).

PS: as i said in the previous comment, you should switch the repo URL on
readme

Thanks again,
i'll try to contribute again when i'll have a little more time available.

Bye,
Sylvain

2015-05-15 12:47 GMT+02:00 Jarrod Linahan <notifications@github.com>:

**Comment by texh** [comment]
Makes sense (time is always fleeting).

I've modified README.md, and also slightly changed the getHistory() function. The callback will now recieve an object that's already been parsed with JSON.parse - see modified example in the README/RTFS if I'm not making sense here.

Also I made note in Todo that we should look at changing the interface to match the iOS plugin [leecrossley/cordova-plugin-pedometer](https://github.com/leecrossley/cordova-plugin-pedometer) in case they could end up merged in the future.

Thanks again
J

**Pull request merged**
